<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE cs [
    <!ELEMENT cs (cn*)>
    <!ELEMENT cn (it*)>
    <!ATTLIST cn nm CDATA #REQUIRED>
    <!ATTLIST cn ct CDATA #REQUIRED>
    <!ELEMENT it EMPTY>
    <!ATTLIST it nm CDATA #REQUIRED>
    <!ATTLIST it vl CDATA #REQUIRED>
    <!ATTLIST it ex CDATA #IMPLIED>
    ]>

<cs>
  <cn nm="afghan" ct="1">
    <it nm="airpol" vl="46.50"/>
    <it nm="humdev" vl="0.496"/>
    <it nm="gayhap" vl="-" ex="pak"/>
    <it nm="lngepi" vl="445"/>
    <it nm="langen" vl="-" ex="iraq"/><!--sudan-->
    <it nm="avgwth" vl="14"/>
    <it nm="sumwin" vl="25.5"/>
    <it nm="crimer" vl="76.97"/>
    <it nm="worisk" vl="9.21"/>
    <it nm="gpeace" vl="3.300"/>
    <it nm="dnganm" vl="~15"/>
    <it nm="suicid" vl="6.4"/>
    <it nm="sunshn" vl="~3175.1"/>
    <it nm="frerel" vl="23.13"/>
    <it nm="frebio" vl="15.63"/>
    <it nm="fredrg" vl="18.75"/>
    <it nm="fresex" vl="0.00"/>
    <it nm="fretht" vl="1100"/>
    <it nm="democr" vl="2.85"/>
    <it nm="traffc" vl="276.95"/>
    <it nm="migacc" vl="2.51"/>
    <it nm="racism" vl="0"/>
    <it nm="bdhair" vl="~37"/>
    <it nm="blonde" vl="~0"/>
    <it nm="intusr" vl="11.45"/>
    <it nm="ginnov" vl="-" ex="pak"/>
    <it nm="gtacoi" vl="-" ex="pak"/>
    <it nm="inflat" vl="3.50"/>
    <it nm="unempl" vl="13.30"/>
    <it nm="conscr" vl="0"/>
    <it nm="mwcosr" vl="5.56"/>
    <it nm="costpr" vl="15.59"/>
  </cn>
  <cn nm="alba" ct="2">
    <it nm="airpol" vl="16.00"/>
    <it nm="humdev" vl="0.791"/>
    <it nm="gayhap" vl="34"/>
    <it nm="lngepi" vl="511"/>
    <it nm="langen" vl="-" ex="ukrain"/>
    <it nm="avgwth" vl="14"/>
    <it nm="sumwin" vl="17.5"/>
    <it nm="crimer" vl="39.86"/>
    <it nm="worisk" vl="8.18"/>
    <it nm="gpeace" vl="1.821"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="5.6"/>
    <it nm="sunshn" vl="2544"/>
    <it nm="frerel" vl="96.13"/>
    <it nm="frebio" vl="62.50"/>
    <it nm="fredrg" vl="19.85"/>
    <it nm="fresex" vl="65.00"/>
    <it nm="fretht" vl="13"/>
    <it nm="democr" vl="5.89"/>
    <it nm="traffc" vl="123.83"/>
    <it nm="migacc" vl="7.22"/>
    <it nm="racism" vl="0"/>
    <it nm="bdhair" vl="~70"/>
    <it nm="blonde" vl="8"/>
    <it nm="intusr" vl="71.85"/>
    <it nm="ginnov" vl="30.34"/>
    <it nm="gtacoi" vl="38.94"/>
    <it nm="inflat" vl="4.60"/>
    <it nm="unempl" vl="10.80"/>
    <it nm="conscr" vl="0"/>
    <it nm="mwcosr" vl="8.85"/>
    <it nm="costpr" vl="25.42"/>
  </cn>
  <cn nm="alger" ct="0">
    <it nm="airpol" vl="20.20"/>
    <it nm="humdev" vl="0.759"/>
    <it nm="gayhap" vl="32"/>
    <it nm="lngepi" vl="442"/>
    <it nm="langen" vl="7"/>
    <it nm="avgwth" vl="17.4"/>
    <it nm="sumwin" vl="17.6"/>
    <it nm="crimer" vl="50.41"/>
    <it nm="worisk" vl="7.66"/>
    <it nm="gpeace" vl="2.219"/>
    <it nm="dnganm" vl="~25"/>
    <it nm="suicid" vl="3.3"/>
    <it nm="sunshn" vl="6533"/>
    <it nm="frerel" vl="22.75"/>
    <it nm="frebio" vl="31.25"/>
    <it nm="fredrg" vl="20.24"/>
    <it nm="fresex" vl="77.50"/>
    <it nm="fretht" vl="454"/>
    <it nm="democr" vl="4.01"/>
    <it nm="traffc" vl="206.08"/>
    <it nm="migacc" vl="-" ex="moroc"/>
    <it nm="racism" vl="0"/>
    <it nm="bdhair" vl="~63"/>
    <it nm="blonde" vl="~0"/>
    <it nm="blonde" vl="~0"/>
    <it nm="intusr" vl="47.69"/>
    <it nm="ginnov" vl="23.98"/>
    <it nm="gtacoi" vl="30.75"/>
    <it nm="inflat" vl="9.80"/>
    <it nm="unempl" vl="12.70"/>
    <it nm="conscr" vl="20"/>
    <it nm="mwcosr" vl="10.49"/>
    <it nm="costpr" vl="17.18"/>
  </cn>
  <!--andor-->
  <!--angol-->
  <!--antigbar-->
  <cn nm="argen" ct="4">
    <it nm="airpol" vl="14.20"/>
    <it nm="humdev" vl="0.830"/>
    <it nm="gayhap" vl="67"/>
    <it nm="lngepi" vl="566"/>
    <it nm="langen" vl="6.52"/>
    <it nm="avgwth" vl="17.4"/>
    <it nm="sumwin" vl="13"/>
    <it nm="crimer" vl="62.26"/>
    <it nm="worisk" vl="3.53"/>
    <it nm="gpeace" vl="1.989"/>
    <it nm="dnganm" vl="~25"/>
    <it nm="suicid" vl="9.1"/>
    <it nm="sunshn" vl="2220.3"/>
    <it nm="frerel" vl="95.67"/>
    <it nm="frebio" vl="26.88"/>
    <it nm="fredrg" vl="71.55"/>
    <it nm="fresex" vl="100.00"/>
    <it nm="fretht" vl="103"/>
    <it nm="democr" vl="7.02"/>
    <it nm="traffc" vl="172.79"/>
    <it nm="migacc" vl="6.51"/>
    <it nm="racism" vl="0"/>
    <it nm="bdhair" vl="~56"/>
    <it nm="blonde" vl="-" ex="spain+ital"/>
    <it nm="intusr" vl="75.81"/>
    <it nm="ginnov" vl="31.95"/>
    <it nm="gtacoi" vl="45.33"/>
    <it nm="inflat" vl="108.80"/>
    <it nm="unempl" vl="6.30"/>
    <it nm="conscr" vl="0"/>
    <it nm="mwcosr" vl="24.86"/>
    <it nm="costpr" vl="23.83"/>
  </cn>
  <cn nm="armen" ct="1">
    <it nm="airpol" vl="24.90"/>
    <it nm="humdev" vl="0.760"/>
    <it nm="gayhap" vl="30"/>
    <it nm="lngepi" vl="494"/>
    <it nm="langen" vl="-" ex="turk"/>
    <it nm="avgwth" vl="7.2"/>
    <it nm="sumwin" vl="25.8"/>
    <it nm="crimer" vl="22.69"/>
    <it nm="worisk" vl="5.72"/>
    <it nm="gpeace" vl="2.294"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="5.7"/>
    <it nm="sunshn" vl="2474"/>
    <it nm="frerel" vl="92.79"/>
    <it nm="frebio" vl="87.50"/>
    <it nm="fredrg" vl="21.36"/>
    <it nm="fresex" vl="40.00"/>
    <it nm="fretht" vl="54"/>
    <it nm="democr" vl="5.54"/>
    <it nm="traffc" vl="116.94"/>
    <it nm="migacc" vl="5.78"/>
    <it nm="racism" vl="93"/>
    <it nm="bdhair" vl="~55"/>
    <it nm="blonde" vl="3"/>
    <it nm="intusr" vl="69.72"/>
    <it nm="ginnov" vl="33.98"/>
    <it nm="gtacoi" vl="43.52"/>
    <it nm="inflat" vl="3.20"/>
    <it nm="unempl" vl="12.70"/>
    <it nm="conscr" vl="100"/>
    <it nm="mwcosr" vl="6.25"/>
    <it nm="costpr" vl="21.50"/>
  </cn>
  <cn nm="austra" ct="3">
    <it nm="airpol" vl="7.60"/>
    <it nm="humdev" vl="0.938"/>
    <it nm="gayhap" vl="64"/>
    <it nm="lngepi" vl="-" ex="uk"/>
    <it nm="langen" vl="97"/>
    <it nm="avgwth" vl="17.3"/>
    <it nm="sumwin" vl="11.7"/>
    <it nm="crimer" vl="41.67"/>
    <it nm="worisk" vl="4.49"/>
    <it nm="gpeace" vl="1.419"/>
    <it nm="dnganm" vl="~55"/>
    <it nm="suicid" vl="11.7"/>
    <it nm="sunshn" vl="2635.5"/><!--Sydney enough-->
    <it nm="frerel" vl="98.13"/>
    <it nm="frebio" vl="43.75"/>
    <it nm="fredrg" vl="32.50"/>
    <it nm="fresex" vl="68.00"/>
    <it nm="fretht" vl="47"/>
    <it nm="democr" vl="9.09"/>
    <it nm="traffc" vl="148.25"/>
    <it nm="migacc" vl="7.98"/>
    <it nm="racism" vl="-" ex="uk"/>
    <it nm="bdhair" vl="~52"/>
    <it nm="blonde" vl="-" ex="uk+uk+uk+uk+uk+uk+uk+uk+uk+china"/>
    <it nm="intusr" vl="86.54"/>
    <it nm="ginnov" vl="50.34"/>
    <it nm="gtacoi" vl="72.53"/>
    <it nm="inflat" vl="7.00"/>
    <it nm="unempl" vl="3.70"/>
    <it nm="conscr" vl="0"/>
    <it nm="mwcosr" vl="45.34"/>
    <it nm="costpr" vl="62.28"/>
  </cn>
  <cn nm="austri" ct="2">
    <it nm="airpol" vl="10.90"/>
    <it nm="humdev" vl="0.914"/>
    <it nm="gayhap" vl="64"/>
    <it nm="lngepi" vl="623"/>
    <it nm="langen" vl="73"/>
    <it nm="avgwth" vl="7"/>
    <it nm="sumwin" vl="19.2"/>
    <it nm="crimer" vl="24.43"/>
    <it nm="worisk" vl="2.87"/>
    <it nm="gpeace" vl="1.291"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="11.4"/>
    <it nm="sunshn" vl="1884"/>
    <it nm="frerel" vl="98.13"/>
    <it nm="frebio" vl="62.50"/>
    <it nm="fredrg" vl="32.50"/>
    <it nm="fresex" vl="100.00"/>
    <it nm="fretht" vl="20"/>
    <it nm="democr" vl="8.29"/>
    <it nm="traffc" vl="80.52"/>
    <it nm="migacc" vl="6.06"/>
    <it nm="racism" vl="46"/>
    <it nm="bdhair" vl="~67"/>
    <it nm="blonde" vl="54"/>
    <it nm="intusr" vl="87.94"/>
    <it nm="ginnov" vl="50.94"/>
    <it nm="gtacoi" vl="68.87"/>
    <it nm="inflat" vl="9.70"/>
    <it nm="unempl" vl="6.20"/>
    <it nm="conscr" vl="100"/>
    <it nm="mwcosr" vl="~25.97"/>
    <it nm="costpr" vl="53.00"/>
  </cn>
  <cn nm="azer" ct="1">
    <it nm="airpol" vl="-" ex="armen"/>
    <it nm="humdev" vl="0.754"/>
    <it nm="gayhap" vl="33"/>
    <it nm="lngepi" vl="432"/>
    <it nm="langen" vl="-" ex="turk"/>
    <it nm="avgwth" vl="13"/>
    <it nm="sumwin" vl="24.1"/>
    <it nm="crimer" vl="32.12"/>
    <it nm="worisk" vl="5.73"/>
    <it nm="gpeace" vl="2.425"/>
    <it nm="dnganm" vl="~15"/>
    <it nm="suicid" vl="2.6"/>
    <it nm="sunshn" vl="2207.4"/>
    <it nm="frerel" vl="53.10"/>
    <it nm="frebio" vl="67.50"/>
    <it nm="fredrg" vl="15.23"/>
    <it nm="fresex" vl="42.50"/>
    <it nm="fretht" vl="82"/>
    <it nm="democr" vl="2.75"/>
    <it nm="traffc" vl="162.23"/>
    <it nm="migacc" vl="4.34"/>
    <it nm="racism" vl="0"/>
    <it nm="bdhair" vl="~54"/>
    <it nm="blonde" vl="~1"/>
    <it nm="intusr" vl="79.00"/>
    <it nm="ginnov" vl="30.21"/>
    <it nm="gtacoi" vl="48.57"/>
    <it nm="inflat" vl="13.50"/>
    <it nm="unempl" vl="6.00"/>
    <it nm="conscr" vl="100"/>
    <it nm="mwcosr" vl="7.15"/>
    <it nm="costpr" vl="20.45"/>
  </cn>
  <cn nm="baham" ct="4">
    <it nm="airpol" vl="~3.30"/><!--Puerto Rico's-->
    <it nm="humdev" vl="0.805"/>
    <it nm="gayhap" vl="-" ex="cuba"/>
    <it nm="lngepi" vl="-" ex="cuba"/>
    <it nm="langen" vl="87.13"/>
    <it nm="avgwth" vl="24.7"/>
    <it nm="sumwin" vl="6.6"/>
    <it nm="crimer" vl="62.74"/>
    <it nm="worisk" vl="4.31"/>
    <it nm="gpeace" vl="-" ex="argen"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="1.6"/>
    <it nm="sunshn" vl="~2963.8"/><!--Puerto Rico's-->
    <it nm="frerel" vl="98.00"/>
    <it nm="frebio" vl="31.25"/>
    <it nm="fredrg" vl="15.87"/>
    <it nm="fresex" vl="62.50"/>
    <it nm="fretht" vl="20"/>
    <it nm="democr" vl="-" ex="dominicrep"/>
    <it nm="traffc" vl="~160.03"/><!--Puerto Rico's-->
    <it nm="migacc" vl="-" ex="usa"/>
    <it nm="racism" vl="0"/>
    <it nm="bdhair" vl="~55"/>
    <it nm="blonde" vl="-" ex="ind+ind+ind+ind+ind+ind+ind+ind+ind+uk"/>
    <it nm="intusr" vl="85.00"/>
    <it nm="ginnov" vl="-" ex="dominicrep"/>
    <it nm="gtacoi" vl="-" ex="dominicrep"/>
    <it nm="inflat" vl="4.60"/>
    <it nm="unempl" vl="13.20"/>
    <it nm="conscr" vl="0"/>
    <it nm="mwcosr" vl="14.90"/>
    <it nm="costpr" vl="61.33"/>
  </cn>
  <cn nm="bahr" ct="1">
    <it nm="airpol" vl="39.70"/>
    <it nm="humdev" vl="0.838"/>
    <it nm="gayhap" vl="-" ex="qtr"/>
    <it nm="lngepi" vl="453"/>
    <it nm="langen" vl="-" ex="pak"/>
    <it nm="avgwth" vl="25.5"/>
    <it nm="sumwin" vl="17.5"/>
    <it nm="crimer" vl="26.86"/>
    <it nm="worisk" vl="2.89"/>
    <it nm="gpeace" vl="2.357"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="5.7"/>
    <it nm="sunshn" vl="-" ex="uae"/>
    <it nm="frerel" vl="15.00"/>
    <it nm="frebio" vl="67.50"/>
    <it nm="fredrg" vl="15.24"/>
    <it nm="fresex" vl="0.00"/>
    <it nm="fretht" vl="387"/>
    <it nm="democr" vl="2.55"/>
    <it nm="traffc" vl="135.23"/>
    <it nm="migacc" vl="-" ex="uae"/>
    <it nm="racism" vl="0"/>
    <it nm="bdhair" vl="~55"/>
    <it nm="blonde" vl="~0"/>
    <it nm="intusr" vl="95.88"/>
    <it nm="ginnov" vl="31.10"/>
    <it nm="gtacoi" vl="50.35"/>
    <it nm="inflat" vl="-0.10"/>
    <it nm="unempl" vl="6.60"/>
    <it nm="conscr" vl="0"/>
    <it nm="mwcosr" vl="~18.02"/>
    <it nm="costpr" vl="44.24"/>
  </cn>
  <!--bangla-->
  <!--barba-->
  <cn nm="belar" ct="2">
    <it nm="airpol" vl="-" ex="ukrain"/>
    <it nm="humdev" vl="0.817"/>
    <it nm="gayhap" vl="37"/>
    <it nm="lngepi" vl="513"/>
    <it nm="langen" vl="-" ex="rus"/>
    <it nm="avgwth" vl="5.9"/>
    <it nm="sumwin" vl="24.9"/>
    <it nm="crimer" vl="25.02"/>
    <it nm="worisk" vl="2.59"/>
    <it nm="gpeace" vl="2.115"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="21.4"/>
    <it nm="sunshn" vl="1676.5"/>
    <it nm="frerel" vl="73.15"/>
    <it nm="frebio" vl="87.50"/>
    <it nm="fredrg" vl="17.36"/>
    <it nm="fresex" vl="22.50"/>
    <it nm="fretht" vl="169"/>
    <it nm="democr" vl="2.48"/>
    <it nm="traffc" vl="109.39"/>
    <it nm="migacc" vl="3.38"/>
    <it nm="racism" vl="84"/>
    <it nm="bdhair" vl="~55"/>
    <it nm="blonde" vl="55"/>
    <it nm="intusr" vl="74.44"/>
    <it nm="ginnov" vl="32.07"/>
    <it nm="gtacoi" vl="-" ex="ukrain"/>
    <it nm="inflat" vl="4.70"/>
    <it nm="unempl" vl="3.90"/>
    <it nm="conscr" vl="20"/>
    <it nm="mwcosr" vl="8.09"/>
    <it nm="costpr" vl="20.42"/>
  </cn>
  <cn nm="belg" ct="2">
    <it nm="airpol" vl="8.90"/>
    <it nm="humdev" vl="0.919"/>
    <it nm="gayhap" vl="67"/>
    <it nm="lngepi" vl="612"/>
    <it nm="langen" vl="60"/>
    <it nm="avgwth" vl="9"/>
    <it nm="sumwin" vl="14.9"/>
    <it nm="crimer" vl="45.29"/>
    <it nm="worisk" vl="2.79"/>
    <it nm="gpeace" vl="1.533"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="15.7"/>
    <it nm="sunshn" vl="1546"/>
    <it nm="frerel" vl="98.00"/>
    <it nm="frebio" vl="95.00"/>
    <it nm="fredrg" vl="73.58"/>
    <it nm="fresex" vl="97.50"/>
    <it nm="fretht" vl="0"/>
    <it nm="democr" vl="7.64"/>
    <it nm="traffc" vl="146.77"/>
    <it nm="migacc" vl="6.16"/>
    <it nm="racism" vl="23"/>
    <it nm="bdhair" vl="~64"/>
    <it nm="blonde" vl="45"/>
    <it nm="intusr" vl="87.68"/>
    <it nm="ginnov" vl="50.18"/>
    <it nm="gtacoi" vl="68.87"/>
    <it nm="inflat" vl="5.60"/>
    <it nm="unempl" vl="5.90"/>
    <it nm="conscr" vl="0"/>
    <it nm="mwcosr" vl="38.02"/>
    <it nm="costpr" vl="53.83"/>
  </cn>
  <!--beliz-->
  <!--benin-->
  <!--bhut-->
  <!--boliv-->
  <cn nm="bosni" ct="2">
    <it nm="airpol" vl="40.60"/>
    <it nm="humdev" vl="0.769"/>
    <it nm="gayhap" vl="33"/>
    <it nm="lngepi" vl="-" ex="serb"/>
    <it nm="langen" vl="-" ex="croat"/>
    <it nm="avgwth" vl="9.7"/>
    <it nm="sumwin" vl="19.4"/>
    <it nm="crimer" vl="43.57"/>
    <it nm="worisk" vl="4.71"/>
    <it nm="gpeace" vl="2.019"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="6.4"/>
    <it nm="sunshn" vl="1769"/>
    <it nm="frerel" vl="92.38"/>
    <it nm="frebio" vl="67.50"/>
    <it nm="fredrg" vl="21.41"/>
    <it nm="fresex" vl="82.50"/>
    <it nm="fretht" vl="160"/>
    <it nm="democr" vl="4.86"/>
    <it nm="traffc" vl="89.98"/>
    <it nm="migacc" vl="2.71"/>
    <it nm="racism" vl="58"/>
    <it nm="bdhair" vl="~67"/>
    <it nm="blonde" vl="19"/>
    <it nm="intusr" vl="94.32"/>
    <it nm="ginnov" vl="31.41"/>
    <it nm="gtacoi" vl="32.77"/>
    <it nm="inflat" vl="10.30"/>
    <it nm="unempl" vl="31.06"/>
    <it nm="conscr" vl="0"/>
    <it nm="mwcosr" vl="10.70"/>
    <it nm="costpr" vl="23.54"/>
  </cn>
  <!--botsw-->
  <cn nm="braz" ct="4">
    <it nm="airpol" vl="14.20"/>
    <it nm="humdev" vl="0.761"/>
    <it nm="gayhap" vl="51"/>
    <it nm="lngepi" vl="490"/>
    <it nm="langen" vl="5"/>
    <it nm="avgwth" vl="24.5"/>
    <it nm="sumwin" vl="3.2"/>
    <it nm="crimer" vl="68.31"/>
    <it nm="worisk" vl="4.79"/>
    <it nm="gpeace" vl="2.271"/>
    <it nm="dnganm" vl="~55"/>
    <it nm="suicid" vl="6.1"/>
    <it nm="sunshn" vl="2189.6"/>
    <it nm="frerel" vl="95.67"/>
    <it nm="frebio" vl="30.63"/>
    <it nm="fredrg" vl="56.03"/>
    <it nm="fresex" vl="100.00"/>
    <it nm="fretht" vl="22"/>
    <it nm="democr" vl="6.86"/>
    <it nm="traffc" vl="177.06"/>
    <it nm="migacc" vl="6.38"/>
    <it nm="racism" vl="0"/>
    <it nm="bdhair" vl="~32"/>
    <it nm="blonde" vl="-" ex="port+port+port+niger+niger"/>
    <it nm="intusr" vl="71.86"/>
    <it nm="ginnov" vl="33.82"/>
    <it nm="gtacoi" vl="38.14"/>
    <it nm="inflat" vl="4.18"/>
    <it nm="unempl" vl="8.80"/>
    <it nm="conscr" vl="20"/>
    <it nm="mwcosr" vl="13.82"/>
    <it nm="costpr" vl="20.50"/>
  </cn>
  <!--brun-->
  <cn nm="bulgar" ct="2">
    <it nm="airpol" vl="27.50"/>
    <it nm="humdev" vl="0.816"/>
    <it nm="gayhap" vl="41"/>
    <it nm="lngepi" vl="579"/>
    <it nm="langen" vl="25"/>
    <it nm="avgwth" vl="9.6"/>
    <it nm="sumwin" vl="20.2"/>
    <it nm="crimer" vl="38.55"/>
    <it nm="worisk" vl="4.08"/>
    <it nm="gpeace" vl="1.607"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="7.9"/>
    <it nm="sunshn" vl="2177"/>
    <it nm="frerel" vl="96.13"/>
    <it nm="frebio" vl="62.50"/>
    <it nm="fredrg" vl="20.63"/>
    <it nm="fresex" vl="100.00"/>
    <it nm="fretht" vl="28"/>
    <it nm="democr" vl="7.03"/>
    <it nm="traffc" vl="103.15"/>
    <it nm="migacc" vl="2.42"/>
    <it nm="racism" vl="68"/>
    <it nm="bdhair" vl="~69"/>
    <it nm="blonde" vl="10"/>
    <it nm="intusr" vl="63.41"/>
    <it nm="ginnov" vl="40.35"/>
    <it nm="gtacoi" vl="45.76"/>
    <it nm="inflat" vl="11.60"/>
    <it nm="unempl" vl="5.40"/>
    <it nm="conscr" vl="0"/>
    <it nm="mwcosr" vl="15.09"/>
    <it nm="costpr" vl="26.09"/>
  </cn>
  <!--burkfa-->
  <!--burund-->
  <!--ivorcoast-->
  <!--cabover-->
  <!--cambod-->
  <!--camer-->
  <cn nm="can" ct="4">
    <it nm="airpol" vl="7.30"/>
    <it nm="humdev" vl="0.922"/>
    <it nm="gayhap" vl="72"/>
    <it nm="lngepi" vl="-" ex="uk"/>
    <it nm="langen" vl="80.10"/>
    <it nm="avgwth" vl="3.6"/>
    <it nm="sumwin" vl="27.9"/><!--!?!-->
    <it nm="crimer" vl="40.64"/>
    <it nm="worisk" vl="3.03"/>
    <it nm="gpeace" vl="1.327"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="10.4"/>
    <it nm="sunshn" vl="2028.04"/>
    <it nm="frerel" vl="98.13"/>
    <it nm="frebio" vl="75.00"/>
    <it nm="fredrg" vl="88.75"/>
    <it nm="fresex" vl="81.00"/>
    <it nm="fretht" vl="73"/>
    <it nm="democr" vl="9.22"/>
    <it nm="traffc" vl="140.45"/>
    <it nm="migacc" vl="8.14"/>
    <it nm="racism" vl="-" ex="uk"/>
    <it nm="bdhair" vl="~55"/>
    <it nm="blonde" vl="-" ex="uk+franc+mexic"/>
    <it nm="intusr" vl="92.70"/>
    <it nm="ginnov" vl="53.88"/>
    <it nm="gtacoi" vl="71.26"/>
    <it nm="inflat" vl="4.40"/>
    <it nm="unempl" vl="5.00"/>
    <it nm="conscr" vl="0"/>
    <it nm="mwcosr" vl="38.02"/>
    <it nm="costpr" vl="52.12"/>
  </cn>
  <!--car-->
  <cn nm="chad" ct="0">
    <it nm="airpol" vl="-" ex="alger"/>
    <it nm="humdev" vl="0.401"/>
    <it nm="gayhap" vl="-" ex="nigeria"/>
    <it nm="lngepi" vl="-" ex="niger"/>
    <it nm="langen" vl="-" ex="niger"/>
    <it nm="avgwth" vl="27.3"/>
    <it nm="sumwin" vl="7.6"/>
    <it nm="crimer" vl="-" ex="nigeria"/>
    <it nm="worisk" vl="11.90"/>
    <it nm="gpeace" vl="2.522"/>
    <it nm="dnganm" vl="~15"/>
    <it nm="suicid" vl="15.5"/>
    <it nm="sunshn" vl="3353.2"/>
    <it nm="frerel" vl="-" ex="nigeria"/>
    <it nm="frebio" vl="-" ex="nigeria"/>
    <it nm="fredrg" vl="-" ex="nigeria"/>
    <it nm="fresex" vl="-" ex="nigeria"/>
    <it nm="fretht" vl="85"/>
    <it nm="democr" vl="1.61"/>
    <it nm="traffc" vl="110.35"/>
    <it nm="migacc" vl="7.26"/>
    <it nm="racism" vl="0"/>
    <it nm="bdhair" vl="~40"/>
    <it nm="blonde" vl="~0"/>
    <it nm="intusr" vl="6.50"/>
    <it nm="ginnov" vl="-" ex="niger"/>
    <it nm="gtacoi" vl="-" ex="nigeria"/>
    <it nm="inflat" vl="9.60"/>
    <it nm="unempl" vl="1.40"/>
    <it nm="conscr" vl="20"/>
    <it nm="mwcosr" vl="~3.61"/>
    <it nm="costpr" vl="-" ex="nigeria"/>
  </cn>
  <cn nm="chil" ct="4">
    <it nm="airpol" vl="19.30"/>
    <it nm="humdev" vl="0.847"/>
    <it nm="gayhap" vl="53"/>
    <it nm="lngepi" vl="523"/>
    <it nm="langen" vl="9.53"/>
    <it nm="avgwth" vl="12.1"/>
    <it nm="sumwin" vl="8.2"/>
    <it nm="crimer" vl="49.60"/>
    <it nm="worisk" vl="12.45"/>
    <it nm="gpeace" vl="1.634"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="9.7"/>
    <it nm="sunshn" vl="2841.78"/>
    <it nm="frerel" vl="94.25"/>
    <it nm="frebio" vl="26.88"/>
    <it nm="fredrg" vl="71.52"/>
    <it nm="fresex" vl="100.00"/>
    <it nm="fretht" vl="35"/>
    <it nm="democr" vl="8.08"/>
    <it nm="traffc" vl="128.07"/>
    <it nm="migacc" vl="5.17"/>
    <it nm="racism" vl="0"/>
    <it nm="bdhair" vl="~53"/>
    <it nm="blonde" vl="-" ex="spain"/>
    <it nm="intusr" vl="82.33"/>
    <it nm="ginnov" vl="36.64"/>
    <it nm="gtacoi" vl="53.96"/>
    <it nm="inflat" vl="9.90"/>
    <it nm="unempl" vl="8.80"/>
    <it nm="conscr" vl="20"/>
    <it nm="mwcosr" vl="15.55"/>
    <it nm="costpr" vl="32.76"/>
  </cn>
  <cn nm="china" ct="1">
    <it nm="airpol" vl="34.70"/>
    <it nm="humdev" vl="0.758"/>
    <it nm="gayhap" vl="41"/>
    <it nm="lngepi" vl="520"/>
    <it nm="langen" vl="0.83"/>
    <it nm="avgwth" vl="13"/>
    <it nm="sumwin" vl="25.4"/>
    <it nm="crimer" vl="31.18"/>
    <it nm="worisk" vl="5.84"/>
    <it nm="gpeace" vl="2.217"/>
    <it nm="dnganm" vl="~25"/>
    <it nm="suicid" vl="8.0"/>
    <it nm="sunshn" vl="2034.56"/>
    <it nm="frerel" vl="39.00"/>
    <it nm="frebio" vl="72.50"/>
    <it nm="fredrg" vl="15.00"/>
    <it nm="fresex" vl="25.00"/>
    <it nm="fretht" vl="351"/>
    <it nm="democr" vl="2.26"/>
    <it nm="traffc" vl="160.05"/>
    <it nm="migacc" vl="5.11"/>
    <it nm="racism" vl="0"/>
    <it nm="bdhair" vl="~8"/>
    <it nm="blonde" vl="~0"/>
    <it nm="intusr" vl="63.33"/>
    <it nm="ginnov" vl="54.82"/>
    <it nm="gtacoi" vl="49.64"/>
    <it nm="inflat" vl="0.10"/>
    <it nm="unempl" vl="5.20"/>
    <it nm="conscr" vl="0"/>
    <it nm="mwcosr" vl="5.89"/>
    <it nm="costpr" vl="30.06"/>
  </cn>
  <cn nm="colom" ct="4">
    <it nm="airpol" vl="15.60"/>
    <it nm="humdev" vl="0.761"/>
    <it nm="gayhap" vl="51"/>
    <it nm="lngepi" vl="448"/>
    <it nm="langen" vl="4.22"/>
    <it nm="avgwth" vl="23.4"/>
    <it nm="sumwin" vl="0.9"/>
    <it nm="crimer" vl="54.94"/>
    <it nm="worisk" vl="6.59"/>
    <it nm="gpeace" vl="2.661"/>
    <it nm="dnganm" vl="~55"/>
    <it nm="suicid" vl="7.0"/>
    <it nm="sunshn" vl="1930.78"/>
    <it nm="frerel" vl="80.00"/>
    <it nm="frebio" vl="52.50"/>
    <it nm="fredrg" vl="80.25"/>
    <it nm="fresex" vl="93.00"/>
    <it nm="fretht" vl="33"/>
    <it nm="democr" vl="7.13"/>
    <it nm="traffc" vl="196.41"/>
    <it nm="migacc" vl="6.13"/>
    <it nm="racism" vl="0"/>
    <it nm="bdhair" vl="~35"/>
    <it nm="blonde" vl="-" ex="spain+spain+niger+niger+niger"/>
    <it nm="intusr" vl="62.26"/>
    <it nm="ginnov" vl="33.00"/>
    <it nm="gtacoi" vl="39.85"/>
    <it nm="inflat" vl="12.82"/>
    <it nm="unempl" vl="10.00"/>
    <it nm="conscr" vl="100"/>
    <it nm="mwcosr" vl="18.72"/>
    <it nm="costpr" vl="20.94"/>
  </cn>
  <!--comor-->
  <!--congo-->
  <!--costar-->
  <cn nm="croat" ct="2">
    <it nm="airpol" vl="21.20"/>
    <it nm="humdev" vl="0.837"/>
    <it nm="gayhap" vl="42"/>
    <it nm="lngepi" vl="599"/>
    <it nm="langen" vl="49"/>
    <it nm="avgwth" vl="12.5"/>
    <it nm="sumwin" vl="18.4"/>
    <it nm="crimer" vl="24.67"/>
    <it nm="worisk" vl="3.96"/>
    <it nm="gpeace" vl="1.645"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="11.5"/>
    <it nm="sunshn" vl="2272"/>
    <it nm="frerel" vl="92.38"/>
    <it nm="frebio" vl="62.50"/>
    <it nm="fredrg" vl="73.82"/>
    <it nm="fresex" vl="65.00"/>
    <it nm="fretht" vl="89"/>
    <it nm="democr" vl="6.57"/>
    <it nm="traffc" vl="100.73"/>
    <it nm="migacc" vl="2.39"/>
    <it nm="racism" vl="57"/>
    <it nm="bdhair" vl="~67"/>
    <it nm="blonde" vl="25"/>
    <it nm="intusr" vl="67.10"/>
    <it nm="ginnov" vl="37.82"/>
    <it nm="gtacoi" vl="43.53"/>
    <it nm="inflat" vl="8.90"/>
    <it nm="unempl" vl="6.10"/>
    <it nm="conscr" vl="0"/>
    <it nm="mwcosr" vl="16.00"/>
    <it nm="costpr" vl="36.57"/>
  </cn>
  <cn nm="cuba" ct="4">
    <it nm="airpol" vl="-" ex="baham"/>
    <it nm="humdev" vl="0.778"/>
    <it nm="gayhap" vl="59"/>
    <it nm="lngepi" vl="512"/>
    <it nm="langen" vl="-" ex="baham"/>
    <it nm="avgwth" vl="25.1"/>
    <it nm="sumwin" vl="4.8"/>
    <it nm="crimer" vl="29.02"/>
    <it nm="worisk" vl="5.70"/>
    <it nm="gpeace" vl="2.073"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="10.1"/>
    <it nm="sunshn" vl="~2963.8"/><!--Puerto Rico's-->
    <it nm="frerel" vl="49.78"/>
    <it nm="frebio" vl="62.50"/>
    <it nm="fredrg" vl="14.85"/>
    <it nm="fresex" vl="57.50"/>
    <it nm="fretht" vl="9"/>
    <it nm="democr" vl="2.84"/>
    <it nm="traffc" vl="-" ex="venez"/>
    <it nm="migacc" vl="6.82"/>
    <it nm="racism" vl="0"/>
    <it nm="bdhair" vl="~45"/>
    <it nm="blonde" vl="-" ex="uk+uk+ind+ind+ind"/>
    <it nm="intusr" vl="49.10"/>
    <it nm="ginnov" vl="-" ex="dominicrep"/>
    <it nm="gtacoi" vl="-" ex="venez"/>
    <it nm="inflat" vl="46.62"/>
    <it nm="unempl" vl="2.80"/>
    <it nm="conscr" vl="100"/>
    <it nm="mwcosr" vl="0.61"/>
    <it nm="costpr" vl="36.12"/>
  </cn>
  <cn nm="cypr" ct="2">
    <it nm="airpol" vl="15.80"/>
    <it nm="humdev" vl="0.873"/>
    <it nm="gayhap" vl="40"/>
    <it nm="lngepi" vl="-" ex="greec"/>
    <it nm="langen" vl="73"/>
    <it nm="avgwth" vl="18.7"/>
    <it nm="sumwin" vl="15.3"/>
    <it nm="crimer" vl="31.57"/>
    <it nm="worisk" vl="2.87"/>
    <it nm="gpeace" vl="1.805"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="4.5"/>
    <it nm="sunshn" vl="3314.1"/>
    <it nm="frerel" vl="94.25"/>
    <it nm="frebio" vl="87.50"/>
    <it nm="fredrg" vl="38.71"/>
    <it nm="fresex" vl="93.75"/>
    <it nm="fretht" vl="82"/>
    <it nm="democr" vl="7.59"/>
    <it nm="traffc" vl="108.24"/>
    <it nm="migacc" vl="5.41"/>
    <it nm="racism" vl="-" ex="greec"/>
    <it nm="bdhair" vl="~70"/>
    <it nm="blonde" vl="-" ex="turk+greec"/>
    <it nm="intusr" vl="80.74"/>
    <it nm="ginnov" vl="48.34"/>
    <it nm="gtacoi" vl="57.47"/>
    <it nm="inflat" vl="3.70"/>
    <it nm="unempl" vl="6.80"/>
    <it nm="conscr" vl="100"/>
    <it nm="mwcosr" vl="~24.70"/>
    <it nm="costpr" vl="44.29"/>
  </cn>
  <cn nm="czech" ct="2">
    <it nm="airpol" vl="12.30"/>
    <it nm="humdev" vl="0.891"/>
    <it nm="gayhap" vl="66"/>
    <it nm="lngepi" vl="580"/>
    <it nm="langen" vl="27"/>
    <it nm="avgwth" vl="6.8"/>
    <it nm="sumwin" vl="18.6"/>
    <it nm="crimer" vl="25.40"/>
    <it nm="worisk" vl="2.99"/>
    <it nm="gpeace" vl="1.383"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="10.5"/>
    <it nm="sunshn" vl="1668"/>
    <it nm="frerel" vl="99.00"/>
    <it nm="frebio" vl="67.50"/>
    <it nm="fredrg" vl="97.05"/>
    <it nm="fresex" vl="100.00"/>
    <it nm="fretht" vl="-" ex="slovak"/>
    <it nm="democr" vl="7.69"/>
    <it nm="traffc" vl="92.70"/>
    <it nm="migacc" vl="2.26"/>
    <it nm="racism" vl="88"/>
    <it nm="bdhair" vl="~62"/>
    <it nm="blonde" vl="56"/>
    <it nm="intusr" vl="78.72"/>
    <it nm="ginnov" vl="49.43"/>
    <it nm="gtacoi" vl="60.91"/>
    <it nm="inflat" vl="12.70"/>
    <it nm="unempl" vl="3.60"/>
    <it nm="conscr" vl="0"/>
    <it nm="mwcosr" vl="18.50"/>
    <it nm="costpr" vl="35.15"/>
  </cn>
  <!--drc-->
  <cn nm="denm" ct="2">
    <it nm="airpol" vl="9.40"/>
    <it nm="humdev" vl="0.930"/>
    <it nm="gayhap" vl="76"/>
    <it nm="lngepi" vl="632"/>
    <it nm="langen" vl="86"/>
    <it nm="avgwth" vl="7.5"/>
    <it nm="sumwin" vl="15.8"/>
    <it nm="crimer" vl="26.09"/>
    <it nm="worisk" vl="2.65"/>
    <it nm="gpeace" vl="1.316"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="9.2"/>
    <it nm="sunshn" vl="1568"/>
    <it nm="frerel" vl="97.13"/>
    <it nm="frebio" vl="88.75"/>
    <it nm="fredrg" vl="39.06"/>
    <it nm="fresex" vl="100.00"/>
    <it nm="fretht" vl="74"/>
    <it nm="democr" vl="9.22"/>
    <it nm="traffc" vl="87.98"/>
    <it nm="migacc" vl="7.09"/>
    <it nm="racism" vl="19"/>
    <it nm="bdhair" vl="~62"/>
    <it nm="blonde" vl="68"/>
    <it nm="intusr" vl="97.10"/>
    <it nm="ginnov" vl="58.44"/>
    <it nm="gtacoi" vl="75.18"/>
    <it nm="inflat" vl="5.30"/>
    <it nm="unempl" vl="2.30"/>
    <it nm="conscr" vl="20"/>
    <it nm="mwcosr" vl="~43.66"/>
    <it nm="costpr" vl="65.16"/>
  </cn>
  <cn nm="djib" ct="0">
    <it nm="airpol" vl="-" ex="ethiop"/>
    <it nm="humdev" vl="0.495"/>
    <it nm="gayhap" vl="46"/>
    <it nm="lngepi" vl="-" ex="ethiop"/>
    <it nm="langen" vl="-" ex="ymn"/>
    <it nm="avgwth" vl="28.5"/>
    <it nm="sumwin" vl="9.7"/>
    <it nm="crimer" vl="67.30"/>
    <it nm="worisk" vl="16.46"/>
    <it nm="gpeace" vl="2.207"/>
    <it nm="dnganm" vl="~15"/>
    <it nm="suicid" vl="8.5"/>
    <it nm="sunshn" vl="3279.0"/>
    <it nm="frerel" vl="26.50"/>
    <it nm="frebio" vl="15.63"/>
    <it nm="fredrg" vl="14.01"/>
    <it nm="fresex" vl="52.50"/>
    <it nm="fretht" vl="140"/>
    <it nm="democr" vl="2.77"/>
    <it nm="traffc" vl="164.59"/>
    <it nm="migacc" vl="-" ex="somali"/>
    <it nm="racism" vl="0"/>
    <it nm="bdhair" vl="~48"/>
    <it nm="blonde" vl="~0"/>
    <it nm="intusr" vl="55.68"/>
    <it nm="ginnov" vl="-" ex="ymn"/>
    <it nm="gtacoi" vl="-" ex="ethiop"/>
    <it nm="inflat" vl="1.90"/>
    <it nm="unempl" vl="27.90"/>
    <it nm="conscr" vl="0"/>
    <it nm="mwcosr" vl="~8.89"/>
    <it nm="costpr" vl="-" ex="somali"/>
  </cn>
  <!--dominic-->
  <cn nm="dominicrep" ct="4">
    <it nm="airpol" vl="~10.21"/><!--Puerto Rico's-->
    <it nm="humdev" vl="0.745"/>
    <it nm="gayhap" vl="40"/>
    <it nm="lngepi" vl="499"/>
    <it nm="langen" vl="-" ex="chil"/>
    <it nm="avgwth" vl="24.8"/>
    <it nm="sumwin" vl="3.7"/>
    <it nm="crimer" vl="61.04"/>
    <it nm="worisk" vl="11.72"/>
    <it nm="gpeace" vl="2.041"/>
    <it nm="dnganm" vl="~5"/>
    <it nm="suicid" vl="10.5"/>
    <it nm="sunshn" vl="~2963.8"/><!--Puerto Rico's-->
    <it nm="frerel" vl="95.13"/>
    <it nm="frebio" vl="0.00"/>
    <it nm="fredrg" vl="18.95"/>
    <it nm="fresex" vl="47.50"/>
    <it nm="fretht" vl="47"/>
    <it nm="democr" vl="6.54"/>
    <it nm="traffc" vl="~160.03"/><!--Puerto Rico's-->
    <it nm="migacc" vl="6.03"/>
    <it nm="racism" vl="0"/>
    <it nm="bdhair" vl="~30"/>
    <it nm="blonde" vl="-" ex="uk+ind+ind"/>
    <it nm="intusr" vl="64.99"/>
    <it nm="ginnov" vl="28.56"/>
    <it nm="gtacoi" vl="37.29"/>
    <it nm="inflat" vl="5.20"/>